version: "2"
run:
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecksumtype
    - gocognit
    - gocritic
    - gocyclo
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    - testableexamples
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 105
      statements: 50
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - rangeValCopy
        - unnamedResult
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G601
        - G115
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - funlen
          - gocognit
          - gocyclo
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: Using the variable on range scope `tt` in function literal
    paths:
      - ^mocks/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - ^mocks/
      - third_party$
      - builtin$
      - examples$
