run:
  # which dirs to skip
  skip-dirs:
    - mocks
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false
  # allow parallel run
  allow-parallel-runners: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
    ignore-words:
      - "cancelled"
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gosec:
    excludes:
      - G601
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - rangeValCopy
      - unnamedResult
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 105
    statements: 50
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    - contextcheck
    - decorder
    # - depguard
    - dogsled
    - dupword
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct TODO: check how to fix it
    - exportloopref
    # - forbidigo TODO: configure forbidden code patterns
    # - forcetypeassert
    - funlen
    - gci
    # - gochecknoglobals TODO: remove globals from code
    # - gochecknoinits TODO: remove main.init
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot
    # - godox
    - goerr113
    - gofmt
    - goimports
    - gomnd
    # - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - gosmopolitan
    - grouper
    - importas
    # - ireturn TODO: not sure if it is a good linter
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    # - staticcheck
    - stylecheck
    # - tagalign
    # - tagliatelle
    - tenv
    - testableexamples
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen TODO: review naming
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - bodyclose
        - gosec
        - dupl
        - gocognit
        - goconst
        - gocyclo
  exclude:
    - Using the variable on range scope `tt` in function literal
