{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeip.fullname" . }}-cluster-role-binding
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeip.serviceAccountName" . }}
    namespace: {{ include "kubeip.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubeip.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
