{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeip-oci-secret
  namespace: {{ .Values.namespaceOverride }}
type: Opaque
data:
  oci_config: {{ .Values.secrets.oci_config }}
  oci_oci_api_key.pem: {{ .Values.secrets.oci_oci_api_key }}
{{- end }}