{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeip.serviceAccountName" . }}
  namespace: {{ include "kubeip.namespace" . }}
  annotations:
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: {{ required "A valid .Values.serviceAccount.annotations.gcpServiceAccountEmail entry required when cloudProvider is gcp" .Values.serviceAccount.annotations.gcpServiceAccountEmail }}
    {{- else if eq .Values.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: {{ required "A valid .Values.serviceAccount.annotations.awsRoleArn entry required when cloudProvider is aws" .Values.serviceAccount.annotations.awsRoleArn }}
    {{- end }}
{{- end }}
