// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	mock "github.com/stretchr/testify/mock"
)

// EipAssigner is an autogenerated mock type for the EipAssigner type
type EipAssigner struct {
	mock.Mock
}

type EipAssigner_Expecter struct {
	mock *mock.Mock
}

func (_m *EipAssigner) EXPECT() *EipAssigner_Expecter {
	return &EipAssigner_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, region, instanceID, address
func (_m *EipAssigner) Assign(ctx context.Context, region string, instanceID string, address *types.Address) error {
	ret := _m.Called(ctx, region, instanceID, address)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *types.Address) error); ok {
		r0 = rf(ctx, region, instanceID, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EipAssigner_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type EipAssigner_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - instanceID string
//   - address *types.Address
func (_e *EipAssigner_Expecter) Assign(ctx interface{}, region interface{}, instanceID interface{}, address interface{}) *EipAssigner_Assign_Call {
	return &EipAssigner_Assign_Call{Call: _e.mock.On("Assign", ctx, region, instanceID, address)}
}

func (_c *EipAssigner_Assign_Call) Run(run func(ctx context.Context, region string, instanceID string, address *types.Address)) *EipAssigner_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*types.Address))
	})
	return _c
}

func (_c *EipAssigner_Assign_Call) Return(_a0 error) *EipAssigner_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EipAssigner_Assign_Call) RunAndReturn(run func(context.Context, string, string, *types.Address) error) *EipAssigner_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// NewEipAssigner creates a new instance of EipAssigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEipAssigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *EipAssigner {
	mock := &EipAssigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
